SmartDataProjects/dynamo

- bin/track_transfers
as well as sorted by Tiers.
Changes to bin/track_transfers only.
> Creating copy status pngs for all incomplete requests individually 

- etc/db/dynamo.sql
- etc/db/dynamohistory.sql
- lib/detox/condition.py
- lib/detox/policy.py
> Production

- lib/detox/policy.py
Implementing protections against invalid dataset names
> Deletion protection

- lib/common/configuration.py
until deleted subscriptions are recovered.
> reverting Express partition definition

- bin/dynamod
We are probably very close to making delta update a production feature again, but for now we comment it out. This is a temporary patch release anyway. We will update the Express partition definition and policies very soon, and can aim to bring back delta update at that point.
> commenting out delta updates

- lib/common/interface/mysqlstore.py
> Wrong block.

- lib/common/interface/mysqlstore.py
Current do_update_blockreplicas only works if groups of blocks are all None.
Make it generic.
> Make do_update_blockreplicas generic

- lib/common/interface/mysqlstore.py
- lib/detox/main.py
Otherwise we'll get intro trouble.
> Protecting update_blockreplicas in test run

- web/html/dynamo/dynamo/dealermon/sites.php
Clyde's work to get the individual graphs of replica transfers.
> Graph function for individual replica transfer

- config/convert_dynamo_locks_config.json
- exec/convert_dynamo_locks
- exec/track_phedex
- exec/track_transfers
- lib/core/impl/mysqlstore.py
- lib/core/inventory.py
- lib/source/impl/phedexdatasetinfo.py
- sbin/dynamo-scheduled
- schedule/cms.seq
Also new feature in scheduler: If a critical executable fails, the sequence crashes.
> Bunch of fixes

- exec/convert_dynamo_locks
- install.sh
- web/install.sh
> Minor fixes

- lib/dataformat/site.py
Backend value was manually set by Max and is used in consistency tool. Need to not overwrite + need a way to automatically update from publicly available sources.
> Temporary fix to make site backend not updatable

- web/html/dynamo/dynamo/dealermon/sites.php
Individual dataset transfers wouldnt show the progress. Reason is a different argument list in the rrd_fetch call (same business as on the main page LHS).
> rrd_fetch function in sites.php

- config/dealer_config.json
- lib/dealer/main.py
- lib/history/impl/mysqlhistory.py
- web/install.sh
> dealer bugfix

- lib/core/impl/mysqlstore.py
- lib/dataformat/site.py
- lib/dealer/main.py
- lib/detox/main.py
- Detox was not updating the inventory after deletions were sent.
- Detox bug in debug logging - was referring to an attr of an object that can be None
- Reduced amount of Dealer log printouts.
> Bugfix and log improvements

- daemon/dynamo-scheduled.sysv
- daemon/dynamod.sysv
- exec/update_replicas_cms
- exec/update_sites_cms
- lib/core/impl/mysqlstore.py
- lib/core/inventory.py
- lib/dataformat/block.py
- lib/dataformat/blockreplica.py
- lib/dataformat/dataset.py
- lib/dataformat/datasetreplica.py
- lib/dataformat/group.py
- lib/dataformat/lfile.py
- lib/dataformat/partition.py
- lib/dataformat/site.py
- lib/dataformat/sitepartition.py
- lib/source/impl/phedexdatasetinfo.py
- utilities/set_quota.py
There were a couple of pretty significant bugs.
- Object deletion logic was not ordered correctly
- update_replicas_cms was leading to a size double count of newly created datasets and blocks
> Important bugfix

- exec/generate_dataset_list_cms
- lib/detox/main.py
- lib/operation/impl/phedexdeletion.py
Was always making block-level deletions. Now fixed.
> detox bugfix

- exec/updater_cms
- lib/core/inventory.py
- lib/dataformat/block.py
- lib/dataformat/blockreplica.py
- lib/dataformat/dataset.py
- lib/dataformat/datasetreplica.py
- lib/dataformat/group.py
- lib/dataformat/lfile.py
- lib/dataformat/partition.py
- lib/dataformat/site.py
- lib/source/impl/phedexdatasetinfo.py
Object deletion happens from the unlink() bottom-up.
> reworked object deletion

- config/dealer_config.json
- config/detox_config.json
- config/updater_config.json
- exec/updater_cms
- lib/source/impl/phedexdatasetinfo.py
- sbin/dynamo-scheduled
- schedule/cms.seq
limit number of sites to query in full update + allow scheduler to repeat single lines.
> Updater was crashing

- config/convert_dynamo_locks_config.json
- config/detox_config.json
- db/dynamoregister.sql
- db/grants.sh
- exec/convert_dynamo_locks
- exec/detox_cms
- lib/operation/applock.py
- lib/operation/impl/mysqlapplock.py
- lib/policy/attrs.py
- lib/policy/predicates.py
- lib/policy/producers/crabaccess.py
- lib/policy/variables.py
- web/cgi-bin/registry/activitylock.class.php
- web/cgi-bin/registry/html/activitylock_help.html
- web/cgi-bin/registry/html/detoxlock_help.html
- web/install.sh
Applock for Unified to coordinate with Dynamo
regex to allow more controlled matching of dataset names
> applock + regex in binary expressions

- config/dealermon_config.json
- exec/track_enforcer
- lib/dealer/plugins/enforcer.py
- lib/enforcer/__init__.py
- lib/enforcer/enforcer.py
- lib/enforcer/interface.py
- schedule/cms.seq
Moving main enforcer logic to a separate lib. Either the enforcer plugin or the track_enforcer are using the class/function, which has different return values depending on whether or not you call it with write_rrd = True/False
> Track enforcer

- config/dealer_config.json
- config/dealermon_config.json
- exec/track_enforcer
- exec/track_phedex
- exec/track_transfers
- lib/dealer/plugins/enforcer.py
- lib/enforcer/__init__.py
- lib/enforcer/interface.py
- enforcer imported from dynamo.enforcer.interface
- EnforcerInterface instantiated with a config object
- If we are including dealer_config from dealermon_config, let's make full use of it
> track_enforcer tweaks

- config/convert_dynamo_locks_config.json
- config/detox_config.json
- config/server_config.json.template
- config/updater_config.json
- db/dynamoregister.sql
- db/grants.sh
- exec/convert_dynamo_locks
- lib/core/impl/mysqlstore.py
- lib/dataformat/block.py
- lib/dealer/dealerpolicy.py
- lib/dealer/main.py
- lib/dealer/plugins/__init__.py
- lib/dealer/plugins/balancer.py
- lib/dealer/plugins/base.py
- lib/dealer/plugins/direct.py
- lib/dealer/plugins/popularity.py
- lib/dealer/plugins/requests.py
- lib/dealer/plugins/undertaker.py
- lib/operation/impl/phedexcopy.py
- lib/utils/interface/mysql.py
- web/cgi-bin/registry/activitylock.class.php
- web/cgi-bin/registry/common.php
- web/cgi-bin/registry/detoxlock.class.php
- web/cgi-bin/registry/detoxlock.php
- web/cgi-bin/registry/invalidation.php
- web/cgi-bin/registry/requests.class.php
- web/cgi-bin/registry/requests.php
- web/install.sh
Changes related to adding registry-based copy / deletion request interface + revamping application lock (to be used by e.g. unified). In addition there are quite some code tweaks to improve performance / readability, which should all be transparent.
I don't think I can really ask for a review with this one - too many changes at once. Sorry about that.
> Whole bunch of updates

- config/convert_dynamo_locks_config.json
- exec/convert_dynamo_locks
- exec/updater_cms
- lib/dataformat/blockreplica.py
- lib/policy/producers/mysqllock.py
- lib/source/impl/phedexreplicainfo.py
- schedule/cms.seq
- web/cgi-bin/registry/detoxlock.class.php
The key was to query phedex with update_since=more than 20 minutes ago. Additionally, to make sure unlocked datasets are fully up-to-date, convert_detox_locks also does a replica update now.
> Fixed delta update

- config/convert_dynamo_locks_config.json
- config/dealer_config.json
- config/dealermon_config.json
- config/track_copy_requests_config.json
- exec/track_copy_requests
- lib/dealer/dealerpolicy.py
- lib/dealer/plugins/requests.py
- lib/enforcer/interface.py
- lib/policy/producers/enforcerprotected.py
- lib/source/impl/phedexreplicainfo.py
- schedule/cms.seq
- web/cgi-bin/dynamo/detox/main.php
- web/cgi-bin/registry/detoxlock.class.php
- web/cgi-bin/registry/requests.class.php
- dealer config fix
- convert locks config fix
- copy requests frontend, backend, and tracker
- detox web bugfix
> enforcer fix + copy requests

- config/dealer_config.json
- db/dynamo.sql
- db/dynamohistory.sql
- db/dynamoregister.sql
- db/grants.sh
- lib/dealer/main.py
- fixed DB grants.
- dealer main was not creating block replicas of newly created dataset replicas.
> db updates and dealer main bugfix

- db/grants.sh
- exec/siteinfo
- schedule/cms.seq
- Updating grants so that siteinfo can run as read-only
- Updating schedule to add caf-alca detox test run (although we don't strictly need this)
> producing caf-alca siteinfo too

- config/updater_config.json
- db/dynamoregister.sql
- lib/dealer/dealerpolicy.py
- lib/dealer/plugins/requests.py
- web/cgi-bin/registry/requests.class.php
For the request API to work with Unified, it needs to be able to accept multiple destinations in one request.
PR tested on desk007.
> Made copy & deletion requests multi-site

- web/html/dynamo/dynamo/dealermon/js/enforcer.js
> Times converted at wrong place

- db/grants.sh
- exec/updater_cms
- lib/dataformat/configuration.py
- lib/source/impl/phedexreplicainfo.py
PhEDEx blockreplicas update_since=X create_since=0 actually didn't work. create_since=0 is ignored and it only returns blocks created within the last 24 hours.
We need to instead query by site. Using the Map parallelization to achieve this.
> delta update yet another fix

- exec/track_copy_requests
- lib/dealer/dealerpolicy.py
- lib/dealer/main.py
- lib/dealer/plugins/requests.py
need to use group info when checking for existing copies.
> bugfix requests

- lib/operation/impl/mysqlapplock.py
- lib/policy/variables.py
> New variables

- config/dealer_config.json
- config/dealer_relval_config.json
- config/detox_config.json
- exec/track_enforcer
- lib/core/server.py
- lib/dealer/plugins/enforcer.py
- lib/enforcer/interface.py
- lib/policy/producers/enforcerprotected.py
- schedule/cms.seq
Enforcer policies are not partition-aware.
Detox enforcer protection also uses part of enforcer/interface.py.
> Using enforcer in a different partition

- config/dealer_config.json
- lib/dealer/plugins/undertaker.py
Adding an option to undertaker to evacuate specific sites.
> undertaker additional sites

- config/updater_config.json
- lib/source/impl/phedexreplicainfo.py
- lib/source/impl/phedexsiteinfo.py
- lib/source/replicainfo.py
- lib/source/siteinfo.py
Excluding them from the configuration now.
> We were not excluding Buffer and Export nodes

- exec/updater_cms
- lib/dealer/plugins/popularity.py
- lib/source/impl/phedexreplicainfo.py
There were cases where we didn't delete empty replicas.
> updater update

- db/dynamohistory.sql
- exec/track_transfers
- lib/dataformat/history.py
- lib/dealer/main.py
- lib/dealer/plugins/base.py
- lib/dealer/plugins/requests.py
- lib/detox/main.py
- lib/history/history.py
- lib/history/impl/mysqlhistory.py
- lib/operation/impl/phedexcopy.py
Good fun for a Friday - major surgery.
We have so far only recorded copied and deleted size per operation. Now we are going to record the sizes per dataset (and at some point we may have to start recording the exact blocks that we copied / deleted).
Passed quick tests on desk007 (detox, dealer, track_transfers).
> major surgery changing the history table schema

- lib/core/server.py
- lib/core/serverutils.py
- sbin/dynamo-server-conf
And proper handling of process exit.
> Letting processes time out

- dynamo.cfg.template
> dropped unused config block

- lib/detox/main.py
- lib/enforcer/interface.py
Stupid bug in enforcer caused petabytes of transfers.
> enforcer and detox bugfix

- exec/track_phedex
- lib/dealer/plugins/requests.py
Was forgetting certain fail cases.
> Crash protection

- lib/dealer/plugins/requests.py
- lib/detox/history.py
- lib/detox/main.py
- lib/enforcer/interface.py
Merging production bugfixes in.
> three-point merge

- lib/enforcer/interface.py
The last bug fix was still not handling partial replicas correctly.
I also restructured the code a bit to make the flow better.
> Logic was still incomplete

- bin/dynamo-inject
- bin/dynamo-request
- defaults.json.template
- install_client.sh
- lib/client/client.py
- lib/client/inject.py
- lib/client/request.py
- lib/dataformat/blockreplica.py
- lib/dataformat/request.py
- lib/detox/history.py
- lib/detox/main.py
- lib/policy/producers/popularity.py
- lib/request/common.py
- lib/utils/interface/webservice.py
- lib/web/modules/inventory/inject.py
- lib/web/modules/request/copy.py
- lib/web/modules/request/deletion.py
- lib/web/modules/request/mixin.py
- lib/web/server.py
- mysql/schema/dynamoregister/deletion_requests.sql
- mysql/schema/dynamoserver/users.sql
- sbin/dynamo-fileopd
- web/js/detox/monitor.js
- web/lighttpd/README
- web/lighttpd/fastcgi.conf
- web/lighttpd/lighttpd.conf
- web/lighttpd/ssl.conf
- General bug fix
- Introduced dynamo.client to be imported by the CLIs
> Fix + factor out client functions

- lib/core/server.py
- lib/detox/history.py
- lib/web/modules/detox/history.py
precedence between cycle and partition was screwed up.
> Detox web fix

- lib/request/copy.py
- lib/request/deletion.py
- lib/web/modules/request/mixin.py
We had forgotten about JSON inputs.
> Bug fix requests API

- lib/history/history.py
- lib/web/modules/detox/locks.py
- mysql/schema/dynamohistory/detox_locks.sql
- mysql/schema/dynamohistory/user_services.sql
Archiving unlocked locks into history
> Detox locks

- lib/web/modules/transfers/history.py
- web/css/transfers/monitor.css
- web/html/transfers/activity.html
- web/js/transfers/activity.js
Everything we love, including mermaids.
> Adding details.

- lib/fileop/history.py
- lib/web/modules/transfers/history.py
- web/js/transfers/activity.js
> Adding plot summary numbers.

- lib/dealer/plugins/requests.py
- lib/detox/history.py
timeout alarm was never canceled!
> bad bug introduced for user data instance

- lib/fileop/history.py
- lib/web/modules/transfers/history.py
- web/html/transfers/activity.html
- web/js/transfers/activity.js
Removing clutter from javascript plot and move it to the python code.
> Tuning of the plot.

- daemon/dynamod.sysv
- install.sh
- lib/core/components/impl/socketappserver.py
- lib/fileop/history.py
- lib/web/modules/inventory/__init__.py
- matplotlib fix
- socketappserver python 2.7 / 2.6 compatibility
- sites API
> bugfix + one new API

- lib/web/modules/transfers/history.py
- lib/web/modules/transfers/monitor.py
- web/html/transfers/activity.html
- web/js/transfers/activity.js
This might actually change the picture a bit. Per default exit_code=0 is requested. Choosing exit_code='!0' will show only failing transfers. Any other integer will work the same way.
> Include exitcode=0 for transfers in selection.

- lib/fileop/history.py
- lib/web/modules/transfers/history.py
- web/css/transfers/monitor.css
- web/html/header_common.html
- web/html/transfers/activity.html
- web/js/transfers/activity.js
Moving towards a more coherent monitoring. Adding some new quantities, but it is clear much more work is needed.
> Include Dynamo logo more coherently/add number of transfers (not volume)

- lib/fileop/history.py
- lib/web/modules/deletions/__init__.py
- lib/web/modules/deletions/history.py
- lib/web/modules/deletions/monitor.py
- web/css/deletions/monitor.css
- web/html/deletions/activity.html
- web/js/deletions/activity.js
... fixing some issues and adding deletions.
> Add Dynamo deletions to the mix and fix some errors.

- lib/web/modules/detox/locks.py
detox lock "set" API was not used by anyone but was actually buggy. Fixed and already deployed in the production area on serv012.
> fixed 'set' API

- Dockerfile
- Jenkinsfile
- Jenkins now builds a container and installs dynamo inside of it
- No meaningful tests yet
> Docker test

- Dockerfile
Just added a step to the Dockerfile to install cx_oracle so that the import doesn't fail
> Add cx_Oracle package for test
